# Generated by Django 3.2.9 on 2021-11-19 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopper',
            new_name='Customer',
        ),
    ]
